---
version: '3'

services:
  app:
    build: .
    ports:
      - 8000:8000
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=solar_db
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - MAILGUN_API_KEY=9e018b1e81a4544227429a66484b8d11-ee16bf1a-c96da913
    depends_on:
      - postgres
  postgres:
    image: postgres:14.1-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=solar_db
    volumes:
      - ./db:/var/lib/postgresql/data
